version: "3.8"
services:
  backend-app:
    build: .
    # image: username/reponname //this is for production only
    ports:
      - "5000:4000"
    environment:
      - PORT=4000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fahim
      - MONGO_INITDB_ROOT_PASSWORD=fahimkhan
    volumes:
      - mongo-db:/data/db
  # redis:
  #   image: redis

volumes:
  mongo-db:
