version: "3.8"
services:
  backend-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/backend
      - /backend/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
