version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  backend-app:
    # deploy: //for docker swarm
    #   replicas: 8
    #   restart_policy:
    #     condition: any
    #   update_config:
    #     parallelism: 2
    #     delay: 15s
    build:
      context: .
      args:
        NODE_ENV: production
    env_file:
      - ./.env
    command: npm start
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
