version: "3.8"
services:
  backend-app:
    build: .
    ports:
      - "3000:4000"
    environment:
      - PORT=4000

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fahim
      - MONGO_INITDB_ROOT_PASSWORD=fahimkhan
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
