export const exploreData = [
  {
    id: '1',
    title: 'burgers',
    iconName: 'hamburger-check',
    iconType: 'material-community',
    navigateScreen: 'burgers',
    highlighted: true,
  },
  {
    id: '2',
    title: 'pizza',
    iconName: 'pizza-outline',
    iconType: 'ionicon',
    navigateScreen: 'pizza',
  },
  {
    id: '3',
    title: 'salads',
    iconName: 'food-apple-outline',
    iconType: 'material-community',
    navigateScreen: 'salads',
  },
  {
    id: '4',
    title: 'sandwiches',
    iconName: 'ios-pizza-sharp',
    iconType: 'ionicon',
    navigateScreen: 'sandwiches',
    highlighted: true,
  },
  {
    id: '5',
    title: 'sides',
    iconName: 'food-variant',
    iconType: 'material-community',
    navigateScreen: 'sides',
    highlighted: true,
  },
  {
    id: '6',
    title: 'beverages',
    iconName: 'bottle-soda-classic-outline',
    iconType: 'material-community',
    navigateScreen: 'beverages',
  },
];
