export const exploreData = [
  {
    id: '1',
    title: 'Patient Portal',
    iconName: 'idcard',
    iconType: 'antdesign',
    navigateScreen: 'PatientPortal',
    highlighted: true,
  },
  {
    id: '2',
    title: 'Doctor',
    iconName: 'users',
    iconType: 'feather',
    navigateScreen: 'Doctor',
  },
  {
    id: '3',
    title: 'Appointment',
    iconName: 'carryout',
    iconType: 'antdesign',
    navigateScreen: 'Appointment',
  },
  {
    id: '4',
    title: 'Health Tips',
    iconName: 'lightbulb-on-outline',
    iconType: 'material-community',
    navigateScreen: 'HealthTips',
  },
  {
    id: '5',
    title: 'Advice / Complain',
    iconName: 'lightbulb-on-outline',
    iconType: 'material-community',
    navigateScreen: 'AdviceComplain',
  },
  {
    id: '6',
    title: 'FAQ',
    iconName: 'head-question-outline',
    iconType: 'material-community',
    navigateScreen: 'Faq',
  },
  {
    id: '7',
    title: 'Gallery',
    iconName: 'images',
    iconType: 'entypo',
    navigateScreen: 'Gallery',
  },
  {
    id: '8',
    title: 'Map',
    iconName: 'map-marker-radius-outline',
    iconType: 'material-community',
    navigateScreen: 'Map',
  },
];
